export {default as AboutSection} from './about'
export {default as ContactSection} from './contact'
export {default as ExperienceSection} from './experience'
export {default as HomeSection} from './home'
export {default as ProjectsSection} from './projects'
export {default as SkillsSection} from './skills'